# create docker agents
version: '3.3'
services:
  ssh-agent:
    container_name: jenkins-agent-1
    ports:
        - '4444:22'
    environment:
        - 'JENKINS_AGENT_SSH_PUBKEY={public key}'
    image: 'jenkins/ssh-agent:alpine'